/* Automatically generated by po2tbl.sed from volnorm.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Normalize Volume Plugin Configurator", 2},
  {"Power level to adjust for", 3},
  {"OK", 4},
  {"Cancel", 5},
  {"Apply", 6},
};

int _msg_tbl_length = 6;
