/* Automatically generated by po2tbl.sed from volnorm.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Volume Normalizing plugin Config", 2},
  {"Target power level", 3},
  {"Silence level", 4},
  {"Maximum Multiplier", 5},
  {"Level", 6},
  {"This", 7},
  {"Currently", 8},
  {"Holds nothing", 9},
  {"Effects", 10},
  {"Use monitor", 11},
  {"Monitor", 12},
  {"OK", 13},
  {"Apply", 14},
  {"Cancel", 15},
  {"Volume Normalizing plugin Monitor", 16},
  {"Couldn't find pixmap file: %s", 17},
  {"Error loading pixmap file: %s", 18},
};

int _msg_tbl_length = 18;
